name: conda-store-server
channels:
  - conda-forge
dependencies:
  # conda environment builds
  - conda
  - conda-docker >= 0.1.3
  - conda-pack
  - conda-lock >=1.0.5
  # web server
  - celery
  - flower
  - redis-py
  - sqlalchemy
  - alembic
  - psycopg2
  - pymysql
  - requests
  - pyyaml
  - uvicorn
  - fastapi
  - pydantic
  - traitlets
  - yarl
  - pyjwt
  - filelock
  - itsdangerous
  - jinja2
  - python-multipart
  # artifact storage
  - minio
