name: conda-store
channels:
  - conda-forge
dependencies:
  # conda environment builds
  - conda-docker
  - conda-pack
  # web server
  - sqlalchemy
  - psycopg2
  - requests
  - flask
  - flask-cors
  - pyyaml
  - pydantic
  # artifact storage
  - minio
