apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - minio.yaml
  - postgres.yaml
  - conda-store-server.yaml
  - conda-store-worker.yaml
configMapGenerator:
  - name: conda-store-config
    files:
      - files/conda_store_config.py
